CC=gcc
ARGS=-Wall -pthread -Werror -o

all: threadHello_step1 matrix_multiplication threadHelloFixed_step1_Fixed
threadHello_step1: threadHello_step1.c
	${CC} threadHello_step1.c ${ARGS} threadHello_step1
matrix_multiplication: matrix_multiplication.c
	${CC} matrix_multiplication.c ${ARGS} matrix_multiplication
threadHelloFixed_step1_Fixed: threadHelloFixed_step1_Fixed.c
	${CC} threadHelloFixed_step1_Fixed.c ${ARGS} threadHelloFixed_step1_Fixed 
