CC=gcc
ARGS=-Wall -pthread -Werror -o

all: threadSync producerConsumer
threadSync: threadSync.c
	${CC} threadSync.c ${ARGS} threadSync
producerConsumer: producerConsumer.c
	${CC} producerConsumer.c ${ARGS} producerConsumer